#include "MD_Display/md_display_iface.h"

#if(boardUSE_OS)
#include "freertos.h"
#include "task.h"
#endif  //boardUSE_OS


unsigned char gsDisplayBuff[25];
 
const unsigned char NUM_COM_SEG_TAB[]=
{	
   LCD_IC1_1A_ICON_COM_INDEX,
   LCD_IC1_1B_ICON_COM_INDEX,
   LCD_IC1_1C_ICON_COM_INDEX,
   LCD_IC1_1D_ICON_COM_INDEX,
   LCD_IC1_1E_ICON_COM_INDEX,
   LCD_IC1_1F_ICON_COM_INDEX,
   LCD_IC1_1G_ICON_COM_INDEX,

  LCD_IC1_1A_ICON_SEG_INDEX, 
  LCD_IC1_1B_ICON_SEG_INDEX,
  LCD_IC1_1C_ICON_SEG_INDEX,
  LCD_IC1_1D_ICON_SEG_INDEX,
  LCD_IC1_1E_ICON_SEG_INDEX,
  LCD_IC1_1F_ICON_SEG_INDEX,
  LCD_IC1_1G_ICON_SEG_INDEX,

  LCD_IC1_2A_ICON_COM_INDEX,
  LCD_IC1_2B_ICON_COM_INDEX,
  LCD_IC1_2C_ICON_COM_INDEX,
  LCD_IC1_2D_ICON_COM_INDEX,
  LCD_IC1_2E_ICON_COM_INDEX,
  LCD_IC1_2F_ICON_COM_INDEX,
  LCD_IC1_2G_ICON_COM_INDEX,

  LCD_IC1_2A_ICON_SEG_INDEX,
  LCD_IC1_2B_ICON_SEG_INDEX,
  LCD_IC1_2C_ICON_SEG_INDEX,
  LCD_IC1_2D_ICON_SEG_INDEX,
  LCD_IC1_2E_ICON_SEG_INDEX,
  LCD_IC1_2F_ICON_SEG_INDEX,
  LCD_IC1_2G_ICON_SEG_INDEX,

  LCD_IC1_3A_ICON_COM_INDEX,
  LCD_IC1_3B_ICON_COM_INDEX,
  LCD_IC1_3C_ICON_COM_INDEX,
  LCD_IC1_3D_ICON_COM_INDEX,
  LCD_IC1_3E_ICON_COM_INDEX,
  LCD_IC1_3F_ICON_COM_INDEX,
  LCD_IC1_3G_ICON_COM_INDEX,

  LCD_IC1_3A_ICON_SEG_INDEX,
  LCD_IC1_3B_ICON_SEG_INDEX,
  LCD_IC1_3C_ICON_SEG_INDEX,
  LCD_IC1_3D_ICON_SEG_INDEX,
  LCD_IC1_3E_ICON_SEG_INDEX,
  LCD_IC1_3F_ICON_SEG_INDEX,
  LCD_IC1_3G_ICON_SEG_INDEX,

  LCD_IC1_4A_ICON_COM_INDEX,
  LCD_IC1_4B_ICON_COM_INDEX,
  LCD_IC1_4C_ICON_COM_INDEX,
  LCD_IC1_4D_ICON_COM_INDEX,
  LCD_IC1_4E_ICON_COM_INDEX,
  LCD_IC1_4F_ICON_COM_INDEX,
  LCD_IC1_4G_ICON_COM_INDEX,

  LCD_IC1_4A_ICON_SEG_INDEX,
  LCD_IC1_4B_ICON_SEG_INDEX,
  LCD_IC1_4C_ICON_SEG_INDEX,
  LCD_IC1_4D_ICON_SEG_INDEX,
  LCD_IC1_4E_ICON_SEG_INDEX,
  LCD_IC1_4F_ICON_SEG_INDEX,
  LCD_IC1_4G_ICON_SEG_INDEX,

  LCD_IC1_5A_ICON_COM_INDEX,
  LCD_IC1_5B_ICON_COM_INDEX,
  LCD_IC1_5C_ICON_COM_INDEX,
  LCD_IC1_5D_ICON_COM_INDEX,
  LCD_IC1_5E_ICON_COM_INDEX,
  LCD_IC1_5F_ICON_COM_INDEX,
  LCD_IC1_5G_ICON_COM_INDEX,

  LCD_IC1_5A_ICON_SEG_INDEX,
  LCD_IC1_5B_ICON_SEG_INDEX,
  LCD_IC1_5C_ICON_SEG_INDEX,
  LCD_IC1_5D_ICON_SEG_INDEX,
  LCD_IC1_5E_ICON_SEG_INDEX,
  LCD_IC1_5F_ICON_SEG_INDEX,
  LCD_IC1_5G_ICON_SEG_INDEX,

  LCD_IC1_6A_ICON_COM_INDEX,
  LCD_IC1_6B_ICON_COM_INDEX,
  LCD_IC1_6C_ICON_COM_INDEX,
  LCD_IC1_6D_ICON_COM_INDEX,
  LCD_IC1_6E_ICON_COM_INDEX,
  LCD_IC1_6F_ICON_COM_INDEX,
  LCD_IC1_6G_ICON_COM_INDEX,

  LCD_IC1_6A_ICON_SEG_INDEX,
  LCD_IC1_6B_ICON_SEG_INDEX,
  LCD_IC1_6C_ICON_SEG_INDEX,
  LCD_IC1_6D_ICON_SEG_INDEX,
  LCD_IC1_6E_ICON_SEG_INDEX,
  LCD_IC1_6F_ICON_SEG_INDEX,
  LCD_IC1_6G_ICON_SEG_INDEX,

  LCD_IC1_7A_ICON_COM_INDEX,
  LCD_IC1_7B_ICON_COM_INDEX,
  LCD_IC1_7C_ICON_COM_INDEX,
  LCD_IC1_7D_ICON_COM_INDEX,
  LCD_IC1_7E_ICON_COM_INDEX,
  LCD_IC1_7F_ICON_COM_INDEX,
  LCD_IC1_7G_ICON_COM_INDEX,

  LCD_IC1_7A_ICON_SEG_INDEX,
  LCD_IC1_7B_ICON_SEG_INDEX,
  LCD_IC1_7C_ICON_SEG_INDEX,
  LCD_IC1_7D_ICON_SEG_INDEX,
  LCD_IC1_7E_ICON_SEG_INDEX,
  LCD_IC1_7F_ICON_SEG_INDEX,
  LCD_IC1_7G_ICON_SEG_INDEX,

  LCD_IC1_8A_ICON_COM_INDEX,
  LCD_IC1_8B_ICON_COM_INDEX,
  LCD_IC1_8C_ICON_COM_INDEX,
  LCD_IC1_8D_ICON_COM_INDEX,
  LCD_IC1_8E_ICON_COM_INDEX,
  LCD_IC1_8F_ICON_COM_INDEX,
  LCD_IC1_8G_ICON_COM_INDEX,

  LCD_IC1_8A_ICON_SEG_INDEX, 
  LCD_IC1_8B_ICON_SEG_INDEX,
  LCD_IC1_8C_ICON_SEG_INDEX,
  LCD_IC1_8D_ICON_SEG_INDEX,
  LCD_IC1_8E_ICON_SEG_INDEX,
  LCD_IC1_8F_ICON_SEG_INDEX,
  LCD_IC1_8G_ICON_SEG_INDEX,

  LCD_IC1_9A_ICON_COM_INDEX,
  LCD_IC1_9B_ICON_COM_INDEX,
  LCD_IC1_9C_ICON_COM_INDEX,
  LCD_IC1_9D_ICON_COM_INDEX,
  LCD_IC1_9E_ICON_COM_INDEX,
  LCD_IC1_9F_ICON_COM_INDEX,
  LCD_IC1_9G_ICON_COM_INDEX,

  LCD_IC1_9A_ICON_SEG_INDEX,
  LCD_IC1_9B_ICON_SEG_INDEX,
  LCD_IC1_9C_ICON_SEG_INDEX,
  LCD_IC1_9D_ICON_SEG_INDEX,
  LCD_IC1_9E_ICON_SEG_INDEX,
  LCD_IC1_9F_ICON_SEG_INDEX,
  LCD_IC1_9G_ICON_SEG_INDEX,

  LCD_IC1_10A_ICON_COM_INDEX,
  LCD_IC1_10B_ICON_COM_INDEX,
  LCD_IC1_10C_ICON_COM_INDEX,
  LCD_IC1_10D_ICON_COM_INDEX,
  LCD_IC1_10E_ICON_COM_INDEX,
  LCD_IC1_10F_ICON_COM_INDEX,
  LCD_IC1_10G_ICON_COM_INDEX,

  LCD_IC1_10A_ICON_SEG_INDEX,
  LCD_IC1_10B_ICON_SEG_INDEX,
  LCD_IC1_10C_ICON_SEG_INDEX,
  LCD_IC1_10D_ICON_SEG_INDEX,
  LCD_IC1_10E_ICON_SEG_INDEX,
  LCD_IC1_10F_ICON_SEG_INDEX,
  LCD_IC1_10G_ICON_SEG_INDEX,

  LCD_IC1_11A_ICON_COM_INDEX,
  LCD_IC1_11B_ICON_COM_INDEX,
  LCD_IC1_11C_ICON_COM_INDEX,
  LCD_IC1_11D_ICON_COM_INDEX,
  LCD_IC1_11E_ICON_COM_INDEX,
  LCD_IC1_11F_ICON_COM_INDEX,
  LCD_IC1_11G_ICON_COM_INDEX,

  LCD_IC1_11A_ICON_SEG_INDEX,
  LCD_IC1_11B_ICON_SEG_INDEX,
  LCD_IC1_11C_ICON_SEG_INDEX,
  LCD_IC1_11D_ICON_SEG_INDEX,
  LCD_IC1_11E_ICON_SEG_INDEX,
  LCD_IC1_11F_ICON_SEG_INDEX,
  LCD_IC1_11G_ICON_SEG_INDEX,

  LCD_IC1_12A_ICON_COM_INDEX,
  LCD_IC1_12B_ICON_COM_INDEX,
  LCD_IC1_12C_ICON_COM_INDEX,
  LCD_IC1_12D_ICON_COM_INDEX,
  LCD_IC1_12E_ICON_COM_INDEX,
  LCD_IC1_12F_ICON_COM_INDEX,
  LCD_IC1_12G_ICON_COM_INDEX,

  LCD_IC1_12A_ICON_SEG_INDEX,
  LCD_IC1_12B_ICON_SEG_INDEX,
  LCD_IC1_12C_ICON_SEG_INDEX,
  LCD_IC1_12D_ICON_SEG_INDEX,
  LCD_IC1_12E_ICON_SEG_INDEX,
  LCD_IC1_12F_ICON_SEG_INDEX,
  LCD_IC1_12G_ICON_SEG_INDEX,
  
  LCD_IC1_13A_ICON_COM_INDEX,
  LCD_IC1_13B_ICON_COM_INDEX,
  LCD_IC1_13C_ICON_COM_INDEX,
  LCD_IC1_13D_ICON_COM_INDEX,
  LCD_IC1_13E_ICON_COM_INDEX,
  LCD_IC1_13F_ICON_COM_INDEX,
  LCD_IC1_13G_ICON_COM_INDEX,

  LCD_IC1_13A_ICON_SEG_INDEX,
  LCD_IC1_13B_ICON_SEG_INDEX,
  LCD_IC1_13C_ICON_SEG_INDEX,
  LCD_IC1_13D_ICON_SEG_INDEX,
  LCD_IC1_13E_ICON_SEG_INDEX,
  LCD_IC1_13F_ICON_SEG_INDEX,
  LCD_IC1_13G_ICON_SEG_INDEX,


  LCD_IC1_14A_ICON_COM_INDEX,
  LCD_IC1_14B_ICON_COM_INDEX,
  LCD_IC1_14C_ICON_COM_INDEX,
  LCD_IC1_14D_ICON_COM_INDEX,
  LCD_IC1_14E_ICON_COM_INDEX,
  LCD_IC1_14F_ICON_COM_INDEX,
  LCD_IC1_14G_ICON_COM_INDEX,

  LCD_IC1_14A_ICON_SEG_INDEX,
  LCD_IC1_14B_ICON_SEG_INDEX,
  LCD_IC1_14C_ICON_SEG_INDEX,
  LCD_IC1_14D_ICON_SEG_INDEX,
  LCD_IC1_14E_ICON_SEG_INDEX,
  LCD_IC1_14F_ICON_SEG_INDEX,
  LCD_IC1_14G_ICON_SEG_INDEX,


  LCD_IC1_15A_ICON_COM_INDEX,
  LCD_IC1_15B_ICON_COM_INDEX,
  LCD_IC1_15C_ICON_COM_INDEX,
  LCD_IC1_15D_ICON_COM_INDEX,
  LCD_IC1_15E_ICON_COM_INDEX,
  LCD_IC1_15F_ICON_COM_INDEX,
  LCD_IC1_15G_ICON_COM_INDEX,

  LCD_IC1_15A_ICON_SEG_INDEX,
  LCD_IC1_15B_ICON_SEG_INDEX,
  LCD_IC1_15C_ICON_SEG_INDEX,
  LCD_IC1_15D_ICON_SEG_INDEX,
  LCD_IC1_15E_ICON_SEG_INDEX,
  LCD_IC1_15F_ICON_SEG_INDEX,
  LCD_IC1_15G_ICON_SEG_INDEX,


  LCD_IC1_16A_ICON_COM_INDEX,
  LCD_IC1_16B_ICON_COM_INDEX,
  LCD_IC1_16C_ICON_COM_INDEX,
  LCD_IC1_16D_ICON_COM_INDEX,
  LCD_IC1_16E_ICON_COM_INDEX,
  LCD_IC1_16F_ICON_COM_INDEX,
  LCD_IC1_16G_ICON_COM_INDEX,

  LCD_IC1_16A_ICON_SEG_INDEX,
  LCD_IC1_16B_ICON_SEG_INDEX,
  LCD_IC1_16C_ICON_SEG_INDEX,
  LCD_IC1_16D_ICON_SEG_INDEX,
  LCD_IC1_16E_ICON_SEG_INDEX,
  LCD_IC1_16F_ICON_SEG_INDEX,
  LCD_IC1_16G_ICON_SEG_INDEX,


  LCD_IC1_17A_ICON_COM_INDEX,
  LCD_IC1_17B_ICON_COM_INDEX,
  LCD_IC1_17C_ICON_COM_INDEX,
  LCD_IC1_17D_ICON_COM_INDEX,
  LCD_IC1_17E_ICON_COM_INDEX,
  LCD_IC1_17F_ICON_COM_INDEX,
  LCD_IC1_17G_ICON_COM_INDEX,

  LCD_IC1_17A_ICON_SEG_INDEX,
  LCD_IC1_17B_ICON_SEG_INDEX,
  LCD_IC1_17C_ICON_SEG_INDEX,
  LCD_IC1_17D_ICON_SEG_INDEX,
  LCD_IC1_17E_ICON_SEG_INDEX,
  LCD_IC1_17F_ICON_SEG_INDEX,
  LCD_IC1_17G_ICON_SEG_INDEX,


  LCD_IC1_18A_ICON_COM_INDEX,
  LCD_IC1_18B_ICON_COM_INDEX,
  LCD_IC1_18C_ICON_COM_INDEX,
  LCD_IC1_18D_ICON_COM_INDEX,
  LCD_IC1_18E_ICON_COM_INDEX,
  LCD_IC1_18F_ICON_COM_INDEX,
  LCD_IC1_18G_ICON_COM_INDEX,

  LCD_IC1_18A_ICON_SEG_INDEX,
  LCD_IC1_18B_ICON_SEG_INDEX,
  LCD_IC1_18C_ICON_SEG_INDEX,
  LCD_IC1_18D_ICON_SEG_INDEX,
  LCD_IC1_18E_ICON_SEG_INDEX,
  LCD_IC1_18F_ICON_SEG_INDEX,
  LCD_IC1_18G_ICON_SEG_INDEX,

  LCD_IC1_19A_ICON_COM_INDEX,
  LCD_IC1_19B_ICON_COM_INDEX,
  LCD_IC1_19C_ICON_COM_INDEX,
  LCD_IC1_19D_ICON_COM_INDEX,
  LCD_IC1_19E_ICON_COM_INDEX,
  LCD_IC1_19F_ICON_COM_INDEX,
  LCD_IC1_19G_ICON_COM_INDEX,

  LCD_IC1_19A_ICON_SEG_INDEX,
  LCD_IC1_19B_ICON_SEG_INDEX,
  LCD_IC1_19C_ICON_SEG_INDEX,
  LCD_IC1_19D_ICON_SEG_INDEX,
  LCD_IC1_19E_ICON_SEG_INDEX,
  LCD_IC1_19F_ICON_SEG_INDEX,
  LCD_IC1_19G_ICON_SEG_INDEX,
};

const unsigned char LCD_NUM_DISP_TAB[]=
{
	0x3F,//0
	0x06,//1
	0x5B,//2
	0x4F,//3
	0x66,//4
	0x6D,//5	
	0x7D,//6
	0x07,//7
	0x7F,//8
	0xEF,//9
	0x40,//-
	0x38,//L
	0x77,//A
	0x7C,//b
	0x58,//c
	0x5E,//d
	0x79,//E
	0x71,//F
	0x74,//h
	0x73,//P
	0x39,//C
	0x76,//H
	0x78,//t
	0x48,//=
	0x5C,//o
	0x54,//n
    0x37,//N
	0x72,//Y
	0x50,//r
	0x3E,//U
};

void delay_us(vu16 us)
{
    vu8 j = 0;
    while(us--)
        for(j = 0; j < 20; j++);
}

void HT_SDA_OUT(void)
{
    gpio_init( dispHT_SDA_PORT,
	           GPIO_MODE_OUT_PP,
	           GPIO_OSPEED_50MHZ,
	           dispHT_SDA_PIN);
}

void HT_SDA_IN(void)
{
    gpio_init( dispHT_SDA_PORT,
	           GPIO_MODE_IPU,
	           GPIO_OSPEED_50MHZ,
	           dispHT_SDA_PIN);
}

void HT_IIC_Start(void)
{
	HT_SDA_OUT();
	dispHT_SDA_H();
	dispHT_SCL_H();
	delay_us(5);
	dispHT_SDA_L();
	delay_us(5);
	dispHT_SCL_L();
}	  

void HT_IIC_Stop(void)
{
	HT_SDA_OUT();
	dispHT_SCL_L();
	dispHT_SDA_L();
 	delay_us(5);
	dispHT_SCL_H();
	delay_us(5);
	dispHT_SDA_H();
	delay_us(5);							   	
}

u8 HT_IIC_Wait_Ack(void)
{
	u16 ucErrTime=0;
	HT_SDA_IN();
	dispHT_SCL_H();
	delay_us(5);
	while(dispHT_READ_SDA())
	{
		ucErrTime++;
		if(ucErrTime>1000)
		{
			HT_IIC_Stop();
			return 1;
		}
	}
    dispHT_SCL_L();	   
	delay_us(5);
	return 0;
} 

void HT_IIC_Ack(void)
{
	dispHT_SCL_L();	
	HT_SDA_OUT();
	dispHT_SDA_L();
	delay_us(2);
	dispHT_SCL_H();
	delay_us(2);
	dispHT_SCL_L();	
}

void HT_IIC_NAck()
{
	dispHT_SCL_L();
	HT_SDA_OUT();
	dispHT_SDA_H();
	delay_us(2);
	dispHT_SCL_H();
	delay_us(2);
	dispHT_SCL_L();	
}					 				     

void HT_IIC_Send_Byte(u8 txd)
{                        
    u8 t=0;   
	HT_SDA_OUT(); 	
	dispHT_SCL_L();
	#if(boardUSE_OS)
	taskENTER_CRITICAL();
	#endif
    for(t=0;t<8;t++)
    {       
        if((txd&0x80)>>7) {dispHT_SDA_H();}
		else              {dispHT_SDA_L();}
        txd<<=1; 	  
		delay_us(5);
		dispHT_SCL_H();
		delay_us(5); 
		dispHT_SCL_L();	
    }
	#if(boardUSE_OS)
    taskEXIT_CRITICAL();
	#endif
}

void Ht1621Wr_Comd(unsigned char command,unsigned char ComData)
{
	HT_IIC_Start();
	HT_IIC_Send_Byte(0x7C);
	HT_IIC_Wait_Ack();
	HT_IIC_Send_Byte(command);
	HT_IIC_Wait_Ack();
	HT_IIC_Send_Byte(ComData);
	HT_IIC_Wait_Ack();
	HT_IIC_Stop();
}

void FillLcdAll1(unsigned char mFillData)
{  
	unsigned char i=0;
	for (i=0;i<25;i++)
	{
		gsDisplayBuff[i]=mFillData;
	}
} 

void FillLcdFromBuff(void)
{	
	unsigned char i=0;
	#if(boardUSE_OS)
	taskENTER_CRITICAL();
	#endif
	HT_IIC_Start();
	HT_IIC_Send_Byte(0x7C);
	HT_IIC_Wait_Ack();
	HT_IIC_Send_Byte(0x80);
	HT_IIC_Wait_Ack();
	HT_IIC_Send_Byte(0x00);
	HT_IIC_Wait_Ack();
	for (i=0;i<25;i++)
	{
		HT_IIC_Send_Byte(gsDisplayBuff[i]);
		HT_IIC_Wait_Ack();
	}
	HT_IIC_Stop();
	#if(boardUSE_OS)
	taskEXIT_CRITICAL();
	#endif
}

void HT1621DispIcon(unsigned char mSegIndex,unsigned char mComIndex)
{
	if (mSegIndex>49)
	return;	 
	if (mComIndex>3)
	return;	
	if (mSegIndex&0x01)
	{
		gsDisplayBuff[(mSegIndex>>1)] |= (1<<(mComIndex+4));
	}
	else
	{  
		gsDisplayBuff[(mSegIndex>>1)] |= (1<<(mComIndex));
	}
} 

void DisplayNum(signed short int mStartX,unsigned char mNum)
{
	unsigned char i=0,tmp=0;
	tmp = LCD_NUM_DISP_TAB[mNum];
	for (i=0;i<7;i++)
	{
		if (tmp&1)
		HT1621DispIcon(NUM_COM_SEG_TAB[mStartX*14+7+i],NUM_COM_SEG_TAB[mStartX*14+i]);
		tmp >>= 1;
	} 	
}

I2cObj_T tLCD_HT1621_IIC;

void HT1621_IfaceInit(void)
{ 	
	rcu_periph_clock_enable(dispLIGHT_POWER_RCU);
	rcu_periph_clock_enable(RCU_AF);
	gpio_pin_remap_config(GPIO_SWJ_SWDPENABLE_REMAP,ENABLE);
    gpio_init( dispLIGHT_POWER_PORT,GPIO_MODE_OUT_PP,GPIO_OSPEED_50MHZ,dispLIGHT_POWER_PIN);
	dispLIGHT_POWER_OFF();
 
	rcu_periph_clock_enable(dispHT_SDA_RCU);
	rcu_periph_clock_enable(dispHT_SCL_RCU);
	
    gpio_init( dispHT_SCL_PORT,
	           GPIO_MODE_OUT_PP,
	           GPIO_OSPEED_50MHZ,
	           dispHT_SCL_PIN);
	 
    gpio_init( dispHT_SDA_PORT,
	           GPIO_MODE_OUT_PP,
	           GPIO_OSPEED_50MHZ,
	           dispHT_SDA_PIN);
	
	gpio_bit_set(dispHT_SCL_PORT,dispHT_SCL_PIN);
	gpio_bit_set(dispHT_SDA_PORT,dispHT_SDA_PIN); 
	
    // vTaskDelay(10);
    
	Ht1621Wr_Comd(0x82,0x00);
	Ht1621Wr_Comd(0x84,0x03);
}

void HT1621_Init(void)
{ 	
	Ht1621Wr_Comd(0x82,0x00);
	Ht1621Wr_Comd(0x84,0x03);
}
